import React, { createContext, useContext, useState, useEffect } from 'react';

export const UI_LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English', dir: 'ltr', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', dir: 'ltr', flag: '🇮🇳' },
  { code: 'ar', label: 'Arabic', nativeLabel: 'العربية', dir: 'rtl', flag: '🇸🇦' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', dir: 'ltr', flag: '🇧🇩' },
  { code: 'ru', label: 'Russian', nativeLabel: 'Русский', dir: 'ltr', flag: '🇷🇺' },
  { code: 'pt', label: 'Portuguese', nativeLabel: 'Português', dir: 'ltr', flag: '🇧🇷' },
  { code: 'ur', label: 'Urdu', nativeLabel: 'اردو', dir: 'rtl', flag: '🇵🇰' },
];

export const TRANSLATIONS = {
  en: {
    nav_challenge: '30-Day Challenge',
    nav_kids: 'Kids Zone',
    nav_start: 'Start Free',
    hero_badge: '🌍 Free Language Learning',
    hero_heading: 'Learn a New Language in 30 Days',
    hero_sub: 'Bite-sized daily lessons, fun quizzes, and a kids zone. No subscription needed.',
    hero_cta: 'Start Free Today',
    hero_kids: 'Kids Zone 🎉',
    select_title: 'Choose Your Language',
    select_sub: 'Pick the language you want to learn',
    dashboard_title: 'Your Progress',
    lesson_new_word: 'NEW WORD',
    lesson_hear: 'Hear it',
    lesson_got_it: 'Got it!',
    lesson_quiz_time: 'QUIZ TIME',
    lesson_what_means: 'What does this mean?',
    lesson_complete: 'Lesson Complete!',
    lesson_continue: 'Continue',
    lesson_saving: 'Saving...',
    lesson_words: 'New Words',
    lesson_quiz_score: 'Quiz Score',
    lesson_xp: 'XP Earned',
    footer_tagline: 'Free language learning for everyone.',
    kids_welcome: "Let's Play!",
    kids_amazing: 'Amazing Job!',
    settings_title: 'Parent Settings',
    lang_switcher_label: 'Interface Language',
  },
  hi: {
    nav_challenge: '30-दिन की चुनौती',
    nav_kids: 'बच्चों का क्षेत्र',
    nav_start: 'मुफ़्त शुरू करें',
    hero_badge: '🌍 मुफ़्त भाषा सीखना',
    hero_heading: '30 दिनों में नई भाषा सीखें',
    hero_sub: 'रोज़ाना छोटे-छोटे पाठ, मज़ेदार प्रश्नोत्तरी और बच्चों का ज़ोन। कोई सदस्यता नहीं चाहिए।',
    hero_cta: 'आज मुफ़्त शुरू करें',
    hero_kids: 'बच्चों का ज़ोन 🎉',
    select_title: 'अपनी भाषा चुनें',
    select_sub: 'वह भाषा चुनें जो आप सीखना चाहते हैं',
    dashboard_title: 'आपकी प्रगति',
    lesson_new_word: 'नया शब्द',
    lesson_hear: 'सुनें',
    lesson_got_it: 'समझ गया!',
    lesson_quiz_time: 'प्रश्नोत्तरी समय',
    lesson_what_means: 'इसका क्या अर्थ है?',
    lesson_complete: 'पाठ पूर्ण!',
    lesson_continue: 'जारी रखें',
    lesson_saving: 'सहेजा जा रहा है...',
    lesson_words: 'नए शब्द',
    lesson_quiz_score: 'प्रश्नोत्तरी स्कोर',
    lesson_xp: 'अर्जित XP',
    footer_tagline: 'सबके लिए मुफ़्त भाषा सीखना।',
    kids_welcome: 'खेलते हैं!',
    kids_amazing: 'शानदार काम!',
    settings_title: 'अभिभावक सेटिंग्स',
    lang_switcher_label: 'इंटरफ़ेस भाषा',
  },
  ar: {
    nav_challenge: 'تحدي 30 يومًا',
    nav_kids: 'منطقة الأطفال',
    nav_start: 'ابدأ مجانًا',
    hero_badge: '🌍 تعلم اللغة مجانًا',
    hero_heading: 'تعلم لغة جديدة في 30 يومًا',
    hero_sub: 'دروس يومية قصيرة، اختبارات ممتعة ومنطقة للأطفال. بدون اشتراك.',
    hero_cta: 'ابدأ مجانًا اليوم',
    hero_kids: 'منطقة الأطفال 🎉',
    select_title: 'اختر لغتك',
    select_sub: 'اختر اللغة التي تريد تعلمها',
    dashboard_title: 'تقدمك',
    lesson_new_word: 'كلمة جديدة',
    lesson_hear: 'استمع',
    lesson_got_it: 'فهمت!',
    lesson_quiz_time: 'وقت الاختبار',
    lesson_what_means: 'ماذا تعني هذه الكلمة؟',
    lesson_complete: 'اكتمل الدرس!',
    lesson_continue: 'متابعة',
    lesson_saving: 'جارٍ الحفظ...',
    lesson_words: 'كلمات جديدة',
    lesson_quiz_score: 'نتيجة الاختبار',
    lesson_xp: 'نقاط مكتسبة',
    footer_tagline: 'تعلم اللغات مجانًا للجميع.',
    kids_welcome: 'هيا نلعب!',
    kids_amazing: 'عمل رائع!',
    settings_title: 'إعدادات الوالدين',
    lang_switcher_label: 'لغة الواجهة',
  },
  bn: {
    nav_challenge: '৩০ দিনের চ্যালেঞ্জ',
    nav_kids: 'শিশুদের জোন',
    nav_start: 'বিনামূল্যে শুরু করুন',
    hero_badge: '🌍 বিনামূল্যে ভাষা শিক্ষা',
    hero_heading: '৩০ দিনে নতুন ভাষা শিখুন',
    hero_sub: 'ছোট ছোট দৈনিক পাঠ, মজার কুইজ এবং শিশুদের জোন। কোনো সাবস্ক্রিপশন দরকার নেই।',
    hero_cta: 'আজই বিনামূল্যে শুরু করুন',
    hero_kids: 'শিশুদের জোন 🎉',
    select_title: 'আপনার ভাষা বেছে নিন',
    select_sub: 'আপনি যে ভাষা শিখতে চান তা বেছে নিন',
    dashboard_title: 'আপনার অগ্রগতি',
    lesson_new_word: 'নতুন শব্দ',
    lesson_hear: 'শুনুন',
    lesson_got_it: 'বুঝেছি!',
    lesson_quiz_time: 'কুইজের সময়',
    lesson_what_means: 'এর অর্থ কী?',
    lesson_complete: 'পাঠ সম্পন্ন!',
    lesson_continue: 'চালিয়ে যান',
    lesson_saving: 'সংরক্ষণ হচ্ছে...',
    lesson_words: 'নতুন শব্দ',
    lesson_quiz_score: 'কুইজ স্কোর',
    lesson_xp: 'অর্জিত XP',
    footer_tagline: 'সবার জন্য বিনামূল্যে ভাষা শিক্ষা।',
    kids_welcome: 'খেলা শুরু করি!',
    kids_amazing: 'অসাধারণ কাজ!',
    settings_title: 'অভিভাবক সেটিংস',
    lang_switcher_label: 'ইন্টারফেস ভাষা',
  },
  ru: {
    nav_challenge: '30-дневный вызов',
    nav_kids: 'Детская зона',
    nav_start: 'Начать бесплатно',
    hero_badge: '🌍 Бесплатное изучение языков',
    hero_heading: 'Выучите новый язык за 30 дней',
    hero_sub: 'Короткие ежедневные уроки, веселые викторины и детская зона. Без подписки.',
    hero_cta: 'Начать бесплатно сегодня',
    hero_kids: 'Детская зона 🎉',
    select_title: 'Выберите язык',
    select_sub: 'Выберите язык, который хотите изучить',
    dashboard_title: 'Ваш прогресс',
    lesson_new_word: 'НОВОЕ СЛОВО',
    lesson_hear: 'Послушать',
    lesson_got_it: 'Понял!',
    lesson_quiz_time: 'ВРЕМЯ ВИКТОРИНЫ',
    lesson_what_means: 'Что это означает?',
    lesson_complete: 'Урок завершён!',
    lesson_continue: 'Продолжить',
    lesson_saving: 'Сохранение...',
    lesson_words: 'Новые слова',
    lesson_quiz_score: 'Счёт викторины',
    lesson_xp: 'Заработано XP',
    footer_tagline: 'Бесплатное изучение языков для всех.',
    kids_welcome: 'Играем!',
    kids_amazing: 'Отличная работа!',
    settings_title: 'Настройки родителей',
    lang_switcher_label: 'Язык интерфейса',
  },
  pt: {
    nav_challenge: 'Desafio de 30 Dias',
    nav_kids: 'Zona Kids',
    nav_start: 'Começar Grátis',
    hero_badge: '🌍 Aprendizado de Idiomas Grátis',
    hero_heading: 'Aprenda um Novo Idioma em 30 Dias',
    hero_sub: 'Lições diárias rápidas, quizzes divertidos e uma zona kids. Sem assinatura.',
    hero_cta: 'Começar Grátis Hoje',
    hero_kids: 'Zona Kids 🎉',
    select_title: 'Escolha Seu Idioma',
    select_sub: 'Escolha o idioma que deseja aprender',
    dashboard_title: 'Seu Progresso',
    lesson_new_word: 'NOVA PALAVRA',
    lesson_hear: 'Ouvir',
    lesson_got_it: 'Entendi!',
    lesson_quiz_time: 'HORA DO QUIZ',
    lesson_what_means: 'O que isso significa?',
    lesson_complete: 'Lição Completa!',
    lesson_continue: 'Continuar',
    lesson_saving: 'Salvando...',
    lesson_words: 'Novas Palavras',
    lesson_quiz_score: 'Pontuação do Quiz',
    lesson_xp: 'XP Ganho',
    footer_tagline: 'Aprendizado de idiomas gratuito para todos.',
    kids_welcome: 'Vamos Brincar!',
    kids_amazing: 'Trabalho Incrível!',
    settings_title: 'Configurações dos Pais',
    lang_switcher_label: 'Idioma da Interface',
  },
  ur: {
    nav_challenge: '30 روزہ چیلنج',
    nav_kids: 'بچوں کا زون',
    nav_start: 'مفت شروع کریں',
    hero_badge: '🌍 مفت زبان سیکھنا',
    hero_heading: '30 دنوں میں نئی زبان سیکھیں',
    hero_sub: 'روزانہ چھوٹے اسباق، مزیدار کوئز اور بچوں کا زون۔ کوئی سبسکرپشن نہیں۔',
    hero_cta: 'آج مفت شروع کریں',
    hero_kids: 'بچوں کا زون 🎉',
    select_title: 'اپنی زبان منتخب کریں',
    select_sub: 'وہ زبان منتخب کریں جو آپ سیکھنا چاہتے ہیں',
    dashboard_title: 'آپ کی پیشرفت',
    lesson_new_word: 'نیا لفظ',
    lesson_hear: 'سنیں',
    lesson_got_it: 'سمجھ گیا!',
    lesson_quiz_time: 'کوئز کا وقت',
    lesson_what_means: 'اس کا کیا مطلب ہے؟',
    lesson_complete: 'سبق مکمل!',
    lesson_continue: 'جاری رکھیں',
    lesson_saving: 'محفوظ ہو رہا ہے...',
    lesson_words: 'نئے الفاظ',
    lesson_quiz_score: 'کوئز اسکور',
    lesson_xp: 'حاصل کردہ XP',
    footer_tagline: 'سب کے لیے مفت زبان سیکھنا۔',
    kids_welcome: 'کھیلتے ہیں!',
    kids_amazing: 'شاندار کام!',
    settings_title: 'والدین کی ترتیبات',
    lang_switcher_label: 'انٹرفیس زبان',
  },
};

const UILanguageContext = createContext(null);

export function UILanguageProvider({ children }) {
  const [langCode, setLangCode] = useState(() => localStorage.getItem('ui_lang') || 'en');

  const currentLang = UI_LANGUAGES.find((l) => l.code === langCode) || UI_LANGUAGES[0];
  const t = TRANSLATIONS[langCode] || TRANSLATIONS.en;

  const setLanguage = (code) => {
    setLangCode(code);
    localStorage.setItem('ui_lang', code);
  };

  // Apply RTL direction to document
  useEffect(() => {
    document.documentElement.dir = currentLang.dir;
    document.documentElement.lang = langCode;
  }, [langCode, currentLang.dir]);

  return (
    <UILanguageContext.Provider value={{ langCode, currentLang, t, setLanguage, languages: UI_LANGUAGES }}>
      {children}
    </UILanguageContext.Provider>
  );
}

export function useUILanguage() {
  return useContext(UILanguageContext);
}